#!/usr/bin/env python3
"""
Encode credentials for Railway deployment
Creates base64 encoded versions of client_secret.json and token.json
"""
import base64
from pathlib import Path

def encode_file(filename):
    """Encode a file to base64"""
    filepath = Path(filename)
    
    if not filepath.exists():
        print(f"✗ {filename} not found")
        return None
    
    try:
        content = filepath.read_text(encoding='utf-8')
        encoded = base64.b64encode(content.encode('utf-8')).decode('utf-8')
        
        output_file = filepath.stem + '_b64.txt'
        Path(output_file).write_text(encoded, encoding='utf-8')
        
        print(f"✓ {filename} encoded to {output_file}")
        return encoded
    except Exception as e:
        print(f"✗ Error encoding {filename}: {e}")
        return None

def main():
    print("\n" + "="*60)
    print("Railway Credential Encoder")
    print("="*60 + "\n")
    
    print("Encoding credentials for Railway deployment...\n")
    
    # Encode client_secret.json
    client_secret = encode_file('client_secret.json')
    
    # Encode token.json
    token = encode_file('token.json')
    
    print("\n" + "="*60)
    
    if client_secret and token:
        print("✓ All credentials encoded successfully!")
        print("\nNext steps:")
        print("1. Copy content from client_secret_b64.txt")
        print("2. In Railway, add variable: YOUTUBE_CLIENT_SECRET_B64")
        print("3. Copy content from token_b64.txt")
        print("4. In Railway, add variable: YOUTUBE_TOKEN_JSON")
        print("5. Add variable: AUTO_UPLOAD_TO_YOUTUBE=true")
        print("\nSee RAILWAY_INSTA_SNAP_DEPLOYMENT.md for full guide")
    elif client_secret:
        print("⚠ client_secret.json encoded, but token.json missing")
        print("\nYou need to generate token.json first:")
        print("1. Run: python insta_snap_youtube.py")
        print("2. Authenticate with YouTube")
        print("3. Run this script again")
    elif token:
        print("⚠ token.json encoded, but client_secret.json missing")
        print("\nYou need client_secret.json from Google Cloud Console")
        print("See GET_CLIENT_SECRET_GUIDE.md for instructions")
    else:
        print("✗ No credentials found")
        print("\nYou need both files:")
        print("1. client_secret.json - from Google Cloud Console")
        print("2. token.json - generated by running the script locally")
        print("\nSee RAILWAY_INSTA_SNAP_DEPLOYMENT.md for full guide")
    
    print("="*60 + "\n")

if __name__ == "__main__":
    main()
